### ISSUE TITLE
test single image

### ISSUE THREAD

**Issue by world2025** [Imageomics/INTR#10]
hello,can you share the inference file for single image?

**Comment by dipanjyoti** [comment]
Hi,

We've introduced a Jupyter Notebook, [demo.ipynb](https://github.com/Imageomics/INTR/blob/main/demo.ipynb), designed for single-image prediction and visualization during the inference process.

To get started:

1. Set up your environment accordingly.
2. Connect to the Jupyter Notebook.
3. Specify the `checkpoint_path` and `image_path` for the image of interest.

Please note that the demo is focused on the CUB dataset.

**Comment by dipanjyoti** [comment]
I hope the reported issue has been addressed and resolved. If you encounter any further issues, please feel free to reopen this or create a new issue. Thanks!
